#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#define TRANSFER_LENGTH 16

char target1[TRANSFER_LENGTH]="11";


uint8_t  g_dest[TRANSFER_LENGTH];
uint8_t  g_src[TRANSFER_LENGTH];
uint8_t  g_out_of_band_received[TRANSFER_LENGTH];
uint32_t g_transfer_complete = 0;
uint32_t g_receive_complete  = 0;
uint32_t g_out_of_band_index = 0;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    /* Define the units to be used with the software delay function */
        const bsp_delay_units_t bsp_delay_units = BSP_DELAY_UNITS_MILLISECONDS;
        /* Set the blink frequency (must be <= bsp_delay_units */
        const uint32_t freq_in_hz = 2;

        /* Calculate the delay in terms of bsp_delay_units */
        const uint32_t delay = bsp_delay_units / freq_in_hz;

        /* Holds level to set for pins */
        bsp_io_level_t pin_level = BSP_IO_LEVEL_LOW;

        R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
        /* init UART */
        R_SCI_UART_Open(&g_uart3_ctrl, &g_uart3_cfg);
        /*   */


        while (1)
        {
            /* Open the transfer instance with initial configuration. */
            R_DTC_Open(&g_transfer1_ctrl, &g_transfer1_cfg);
            /* Enable the DTC to handle incoming transfer requests. */
            R_DTC_Enable(&g_transfer1_ctrl);

            R_SCI_UART_Read(&g_uart3_ctrl, target1, TRANSFER_LENGTH);

        //    sprintf(target1, "%d\n", num1);

            R_SCI_UART_Write(&g_uart3_ctrl,target1,TRANSFER_LENGTH);


            //R_SCI_UART_Write(&g_uart3_ctrl,"Not",5);
            /* Write to this pin */
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED1, pin_level);

            /* Toggle level for next write */
            if (BSP_IO_LEVEL_LOW == pin_level)
            {
                pin_level = BSP_IO_LEVEL_HIGH;
            }
            else
            {
                pin_level = BSP_IO_LEVEL_LOW;
            }

            /* Delay */
            R_BSP_SoftwareDelay(delay, bsp_delay_units);
        }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
